CREATE TABLE IF NOT EXISTS Jobs (
	idJob SERIAL PRIMARY KEY NOT NULL,
	idAppeal INTEGER NOT NULL,
	startTime INTEGER NOT NULL,
	complexity TEXT NOT NULL,
	STATUS TEXT NOT NULL,
	FOREIGN KEY(idAppeal) REFERENCES Appeals(idAppeal)
);
